var mobile = [
    {
        title: "Samsung Galaxy S20 5G Factory Unlocked",
        img: "https://www.notebookcheck.net/uploads/tx_nbc2/SamsungGalaxyS20Ultra__1_.JPG",
        img2: "https://images-na.ssl-images-amazon.com/images/I/41QAB6NyEsL._AC_SY879_.jpg",
        img3: "https://images-na.ssl-images-amazon.com/images/I/71h1NfW14xL._AC_SX425_.jpg",
        img4: "https://images-na.ssl-images-amazon.com/images/I/61-hkTJ6MDL._AC_SY741_.jpg",
        img5: "https://images-na.ssl-images-amazon.com/images/I/61MXdL2jpOL._AC_SY741_.jpg",
        brand: "Samsung",
        variant: [
            "128GB",
            "512GB"
        ],
        featuresTitle: [
            "Service Provider",
            "Brand",
            "Display Size",
            "Operating System",
            "Memory Storage Capacity",
        ],
        featuresValue: [
            "Unlocked",
            "Samsung Electronics",
            "6.9 Inches",
            "Android",
        ],
        about: [
            "Power of 5G: Get next-level power for everything you love to do with Samsung Galaxy 5G; Share more, game harder, experience more and never miss a beat",
            "Single Take AI: Capture video and multiple types of images with one tap of the shutter button; Lenses, effects and filters capture the best of every moment, every time",
            "Hires Camera Zoom: Capture hires images from 300 feet away that look like they were taken from 3 feet away; The game-changing new 100x Space Zoom delivers unprecedented power and clarity",
            "Ultra Bright Night Mode: Capture pro-quality content in Ultra Bright Night mode to capture dazzling, blur-free photos and vivid HRD video without flash, even in low light",
            "Super Fast Charging: Charge up quicker with Super Fast Charge so you can keep moving, with more juice; Give your buds – or Galaxy Buds – a boost of power with Wireless PowerShare right from Galaxy S20 Ultra 5G",
            "All-day Battery: S20 Ultra 5G’s intelligent battery uses an algorithm to learn from how you live to optimize power and take you through a day or more of work and life without ever giving out on you",
        ],
        v1Price: 1399,
        v2Price: 1599,
        catagories: "mobile",
        id: 'RY57U6HJTY6U657TGYH76TYUTYUYTU6T76',
    },
    {
        title: "Samsung Galaxy A21 Factory Unlocked",
        img: "https://image-us.samsung.com/SamsungUS/home/mobile/phones/galaxy-a/galaxy-a21/pdp/06092020/PDP-GALLERY-A21-black-01-1600x1200.jpg?$product-details-jpg$",
        img2: "https://image-us.samsung.com/SamsungUS/home/mobile/phones/galaxy-a/galaxy-a21/pdp/06092020/PDP-GALLERY-A21-black-02-1600x1200.jpg?$product-details-jpg$",
        img3: "https://image-us.samsung.com/SamsungUS/home/mobile/phones/galaxy-a/galaxy-a21/pdp/06092020/PDP-GALLERY-A21-black-03-1600x1200.jpg?$product-details-jpg$",
        img4: "https://image-us.samsung.com/SamsungUS/home/mobile/phones/galaxy-a/galaxy-a21/pdp/06092020/PDP-GALLERY-A21-black-04-1600x1200.jpg?$product-details-jpg$",
        img5: "https://images-na.ssl-images-amazon.com/images/I/81JTZOBESHL._AC_SL1500_.jpg",
        brand: "Samsung",
        variant: [
            "32 GB",
        ],
        featuresTitle: [
            "Service Provider",
            "Brand	Samsung",
            "Display Size",
            "Operating System",
            "Memory Storage Capacity",
        ],
        featuresValue: [
            "Unlocked",
            "Electronics",
            "6.5 Inches",
            "Android 10.0",
        ],
        about: [
            "Charge Up. Power Through: Spend more time scrolling, texting and sharing, and less time looking for an outlet to charge your mobile phone; Its long-lasting battery has the power to keep up with you",
            "A Lens for Your Favorite Angle: Capture shareable cell phone portraits, wide shots and videos with the Samsung Galaxy A21’s versatile, 16MP triple-lens camera Big Screen to Get More Done: Keep in touch with friends, family and the news with plenty of room on a crystal-clear, 6.5 edge-to-edge display screen",
            "Store More: Keep all your photos and apps on your Android smart phone without worrying about storage; Get up to 512GB of storage with a MicroSD card (sold separately)",
            "Wireless voice, data and messaging services compatible with most major U. S. GSM and CDMA networks; Support for certain features and services such as VoWiFi and hot spot, vary by wireless service provider",
        ],
        v1Price: 129,
        catagories: "mobile",
        id: 'DFGKJN6556643553FDIJGDFGFDG',
    },
    {
        title: "Samsung Galaxy Note 20",
        img: "https://images.samsung.com/us/smartphones/galaxy-note20/pdp/gallery/canvas1/Bronze/Gallery-01-C1-Lockup-MysticBronze-1600x1200.jpg",
        img2: "https://images.samsung.com/us/smartphones/galaxy-note20/pdp/gallery/canvas1/Bronze/Gallery-03-C1-Back-MysticBronze-1600x1200.jpg",
        img3: "https://images-na.ssl-images-amazon.com/images/I/51f8QKnSnDL._AC_SL1000_.jpg",
        img4: "https://images-na.ssl-images-amazon.com/images/I/41fdLkad2LL._AC_SL1000_.jpg",
        img5: "https://images-na.ssl-images-amazon.com/images/I/61qmQ0PfBKL._AC_SL1000_.jpg",
        brand: "Samsung",
        variant: [
            "Mystic Bronze",
            "Mystic Gray",
            "Mystic Green",
        ],
        featuresTitle: [
            "Service Provider",
            "Brand	Samsung",
            "Display Size",
            "Operating System",
            "Memory Storage Capacity",
        ],
        featuresValue: [
            "T-Mobile",
            "Electronics",
            "6.3 Inches",
            "Android",
            "256 GB",
        ],
        v1Price: 824,
        v2Price: 824,
        v3Price: 669,
        id: 'R6756756GYHJT6Y6UTYUT67RTHRTYU',
        catagories: "mobile",
    },
    {
        title: "Samsung Galaxy Note 10",
        img: "https://image-us.samsung.com/us/smartphones/galaxy-note10/gallery/aura_white/001_gallery_D1_AuraWhite_front_w_pen.jpg",
        img2: "https://image-us.samsung.com/us/smartphones/galaxy-note10/gallery/aura_white/002_gallery_D1_AuraWhite_back_w_pen.jpg",
        img3: "https://image-us.samsung.com/us/smartphones/galaxy-note10/gallery/pens/011_gallery_D1_AuraWhite_pen_front.jpg",
        img4: "https://image-us.samsung.com/us/smartphones/galaxy-note10/gallery/aura_white/003_gallery_D1_AuraWhite_left_front.jpg",
        img5: "https://images-na.ssl-images-amazon.com/images/I/61Qf3dkpcbL._AC_SL1500_.jpg",
        brand: "Samsung",
        variant: [
            "Aura Black",
        ],
        featuresTitle: [
            "Service Provider",
            "Brand	Samsung",
            "Display Size",
            "Operating System",
            "Memory Storage Capacity",
        ],
        featuresValue: [
            "T-Mobile",
            "Electronics",
            "6.3 Inches",
            "Android",
            "256 GB",
        ],
        v1Price: 498,
        catagories: "mobile",
        id: 'RY5R476TYURTY456YRRTHRTTRTYTY',
    },
    {
        title: "Samsung Galaxy Note 10+ Factory Unlocked ",
        img: "https://image-us.samsung.com/us/smartphones/galaxy-note10/gallery/aura_black_n10plus/21_RFP_4A22i14CI_2_Front_Back_LockUps_AuraBlack_RGB.jpg",
        img2: "https://images-na.ssl-images-amazon.com/images/I/61LGgNjwg1L._AC_SL1500_.jpg",
        img3: "https://images-na.ssl-images-amazon.com/images/I/71JrruhVQ3L._AC_SL1500_.jpg",
        img4: "",
        img5: "",
        brand: "Samsung",
        variant: [
            "256GB",
            "512GB",
        ],
        featuresTitle: [
            "Service Provider",
            "Brand",
            "Display Size",
            "Operating System",
            "Memory Storage Capacity",
        ],
        featuresValue: [
            "Unlocked",
            "Samsung Electronics",
            "6.8 Inches",
            "Android",
            "512 GB",
        ],
        v1Price: 999,
        v2Price: 1199,
        catagories: "mobile",
        id: '7UFHJNTGHJ6T77R4576YGFHJTYUTYUYUTUYT',
        rating: 3.2,
    },
    {
        title: "Samsung Galaxy S10 Lite New Unlocked",
        img: "https://www.gizmochina.com/wp-content/uploads/2019/11/Screenshot_3-500x500.jpg",
        img2: "https://images-na.ssl-images-amazon.com/images/I/61ChDFI70ML._AC_SL1500_.jpg",
        img3: "",
        img4: "",
        img5: "",
        brand: "Samsung",
        variant: [
            "128GB",
        ],
        featuresTitle: [
            "Service Provider",
            "Brand",
            "Display Size",
            "Operating System",
            "Memory Storage Capacity",
        ],

        featuresValue: [
            "Unlocked",
            "Samsung Electronics",
            "6.1 Inches",
            "Android 9.0",
        ],
        v1Price: 599,
        catagories: "mobile",
        id: '7UFHJN2343455DRETRTTRT5454YUTUYT',
        rating: 3.2,
        numOfReviews: 12,
    },
    {
        title: "Samsung Galaxy A71 5G Unlocked",
        img: "https://i.gadgets360cdn.com/large/samsung_galaxy_a71_image_1582094305265.jpg",
        img2: "https://m.media-amazon.com/images/I/719CUSPTsgL._AC_SL1500_.jpg",
        img3: "https://m.media-amazon.com/images/I/61bpUh46nKL._AC_SL1500_.jpg",
        img4: "",
        img5: "",
        brand: "Samsung",
        variant: [
            "",
        ],
        featuresTitle: [

        ],

        featuresValue: [

        ],
        v1Price: 369,
        catagories: "mobile",
        id: 'ERTYGFDGBR5YHBFGYT54R7Y45RHYT67657567',
        rating: 3.2,
        numOfReviews: 12,
    },
    {
        title: "Samsung Galaxy M20",
        img: "https://www.notebookcheck.net/fileadmin/_processed_/c/4/csm_Samsung_Galaxy_M20_Teaser_ddcfd1c254.jpg",
        img2: "https://images-na.ssl-images-amazon.com/images/I/51f0DsausnL._AC_SL1500_.jpg",
        img3: "https://images-na.ssl-images-amazon.com/images/I/61z72xovXcL._AC_SL1500_.jpg",
        img4: "",
        img5: "",
        brand: "Samsung",
        variant: [
            "16GB",
        ],
        featuresTitle: [
            "Brand",
            "Display Size",
            "Operating System",
            "Memory Storage Capacity",
            "Color",
        ],

        featuresValue: [
            "Samsung Electronics",
            "6.3 Inches",
            "Android",
            "64 GB",
            "Charcoal Black",
        ],
        v1Price: 129,
        catagories: "mobile",
        id: 'UYVGHNTY675546YTGFEDR54G6TYFD4RTG',
        rating: 3.2,
        numOfReviews: 12,
    },
    {
        title: "Samsung Galaxy S20 FE 5G",
        img: "https://image-us.samsung.com/SamsungUS/home/mobile/phones/galaxy-s/galaxy-s20-fe-5g-images/cloud-navy/PDP-GALLERY-S20-FE-cloud-Navy-Lockup-01-1600x1200.jpg?$product-card-small-jpg$",
        img2: "https://image-us.samsung.com/SamsungUS/home/mobile/phones/galaxy-s/galaxy-s20-fe-5g-images/cloud-navy/PDP-GALLERY-S20-FE-cloud-Navy-02-1600x1200.jpg?$product-card-small-jpg$",
        img3: "https://image-us.samsung.com/SamsungUS/home/mobile/phones/galaxy-s/galaxy-s20-fe-5g-images/cloud-navy/PDP-GALLERY-S20-FE-cloud-Navy-03-1600x1200.jpg?$product-card-small-jpg$",
        img4: "https://image-us.samsung.com/SamsungUS/home/mobile/phones/galaxy-s/galaxy-s20-fe-5g-images/cloud-navy/PDP-GALLERY-S20-FE-cloud-Navy-04-1600x1200.jpg?$product-card-small-jpg$",
        img5: "https://images-na.ssl-images-amazon.com/images/I/61X3Z-gRI-L._AC_SL1500_.jpg",
        brand: "Samsung",
        variant: [
            "Cloud Green",

            "Cloud Lavender",

            "Cloud Navy",

            "Cloud Orange",

            "Cloud Red",

            "Cloud White",
        ],
        featuresTitle: [
            "Service Provider",
            "Brand",
            "Display Size",
            "Operating System",
            "Memory Storage Capacity",
        ],

        featuresValue: [
            "Unlocked",
            "Samsung Electronics",
            "6.5 Inches",
            "Android",
            "128 GB",
        ],
        v1Price: 699,
        v2Price: 699,
        v3Price: 699,
        v4Price: 699,
        v5Price: 699,
        v6Price: 699,
        catagories: "mobile",
        id: '345ETDFTGERT5464R5YRTY',
        rating: 3.2,
        numOfReviews: 12,
    },
    {
        title: "OPPO A33 3GB/32GB",
        img: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/o/p/oppo-a33-4.jpg",
        img2: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/o/p/oppo-a33-3.jpg",
        img3: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/o/p/oppo-a33-5.jpg",
        img4: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/o/p/oppo-a33-2.jpg",
        img5: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/o/p/oppo-a33-6.jpg",
        brand: "OPPO",
        variant: [
            "32GB",
        ],
        featuresTitle: [
            "OS",
            "CPU",
            "CPU Cores",
            "GPU",
            "RAM",
            "ROM",
            "Rear Camera",
            "Front Camera",
            "Screen",
            "Display Panel",
            "Resolution",
            "Battery",
            "Connectivity",
            "",
            "Sensors",
        ],

        featuresValue: [
            "ColorOS 7.2 based on Android 10",
            "Snapdragon 460 (11 nm)",
            "Octa-core",
            "Adreno 610 @600MHz 16fps",
            "3GB",
            "32GB (Support max to 256GB MicroSD)",
            "13MP+2MP+2MP",
            "8MP",
            "6.5 inches",
            "LCD (A-Si)",
            "1600×720 (Refresh Rate: up to 90Hz)",
            "Non-removable Li-Po 5000 mAh battery (Support 9V/2A charging)",
            "WLAN 2.4G/WLAN 5.1G/WLAN 5.8G, WLAN Display, 802.11a/b/g/n/ac. Bluetooth: Bluetooth 5.0",
            "Fingerprint (rear-mounted), accelerometer, proximity, compass",
        ],
        v1Price: 120,
        id: '567GHY55UYVGHNTY6756U7HGN76Y56',
        catagories: "mobile",
        rating: 3.2,
        numOfReviews: 12,
    },
    {
        title: "OPPO Reno 4 8GB/128GB",
        img: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/o/p/oppo-reno-4-3.jpg",
        img2: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/o/p/oppo-reno-4-2.jpg",
        img3: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/o/p/oppo-reno-4-6.jpg",
        img4: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/o/p/oppo-reno-4-5.jpg",
        img5: "",
        brand: "OPPO",
        variant: [
            "128GB",
        ],
        featuresTitle: [
            "OS",
            "CPU",
            "CPU Cores",
            "GPU",
            "RAM",
            "ROM",
            "Rear Camera",
            "Front Camera",
            "Screen",
            "Display Panel",
            "Resolution",
            "Battery",
            "Connectivity",
            "",
            "Sensors",
        ],

        featuresValue: [
            "Android 10, ColorOS 7.2",
            "Qualcomm Snapdragon 720G",
            " Adreno™ 618",
            "8GB",
            "128 GB",
            "48MP+8MP+2MP+2MP",
            "32 MP",
            "6.4 inches",
            "OLED",
            "2400*1080 pixels (FHD+)",
            "Non-removable Li-Po 4015 mAh battery",
            "WLAN: WLAN 2.4GHz / WLAN 5.1GHz / WLAN 5.4GHz / WLAN 5.8GHz. Bluetooth v5.1",
            "Support Geomagnetic sensor, Proximity sensor, Light sensor, G-sensor, Acceleration sensor, Gyroscope, Supports step counting",
        ],
        v1Price: 329,
        id: '57FHYT76GH67GYJTYUYHG65ER3E45FGE5',
        catagories: "mobile",
        rating: 3.2,
        numOfReviews: 12,
    },
    {
        title: "OPPO F17 Pro 8GB/128GB",
        img: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/o/p/oppo-f17-pro-5.jpg",
        img2: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/o/p/oppo-f17-pro-9.jpg",
        img3: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/o/p/oppo-f17-pro.jpg",
        img4: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/o/p/oppo-f17-pro-3.jpg",
        img5: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/o/p/oppo-f17-pro-6.jpg",
        brand: "OPPO",
        variant: [
            "128GB",
        ],
        featuresTitle: [
            "OS",
            "CPU",
            "CPU Cores",
            "GPU",
            "RAM",
            "ROM",
            "Rear Camera",
            "Front Camera",
            "Screen",
            "Display Panel",
            "Resolution",
            "Battery",
            "Connectivity",
            "",
            "Sensors",
        ],

        featuresValue: [
            "ColorOS 7.2 (Based on Android 10)",
            "MediaTek Helio P95",
            "Octa-core",
            "IMG 9XM-HP8 970MHz",
            "8GB",
            "128 GB",
            "48MP+8MP+2MP+2MP",
            "16MP+2MP",
            "6.43 inches",
            "Super AMOLED",
            "2400*1080 (Refresh Rate: up to 60Hz)",
            " Non-removable Li-Po 4015 mAh battery (Fast Charge: VOOC 4.0)",
            "WLAN 2.4G, WLAN 5.1G, WLAN 5.8G, WLAN Display. Bluetooth Version: Bluetooth v5.1",
            "Fingerprint (under display, optical), accelerometer, gyro, proximity, compass",
        ],
        v1Price: 229,
        id: '765656687453534FDFGDFGDFG5453',
        catagories: "mobile",
        rating: 3.2,
        numOfReviews: 12,
    },
    {
        title: "OPPO F17 8GB/128GB",
        img: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/o/p/oppo-f17-4.jpg",
        img2: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/o/p/oppo-f17-2.jpg",
        img3: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/o/p/oppo-f17-3.jpg",
        img4: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/o/p/oppo-f17-front.jpg",
        img5: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/o/p/oppo-f17-8.jpg",
        brand: "OPPO",
        variant: [
            "128GB",
        ],

        featuresTitle: [
            "OS",
            "CPU",
            "CPU Cores",
            "GPU",
            "RAM",
            "ROM",
            "Rear Camera",
            "Front Camera",
            "Screen",
            "Display Panel",
            "Resolution",
            "Battery",
            "Connectivity",
            "",
            "",
            "Sensors",
        ],

        featuresValue: [
            "ColorOS 7.2 (Based on Android 10)",
            "MediaTek Helio P95",
            "Octa-core",
            "IMG 9XM-HP8 970MHz",
            "8GB",
            "128 GB",
            "48MP+8MP+2MP+2MP",
            "16MP+2MP",
            "6.43 inches",
            "Super AMOLED",
            "2400*1080 (Refresh Rate: up to 60Hz)",
            " Non-removable Li-Po 4015 mAh battery (Fast Charge: VOOC 4.0)",
            "WLAN 2.4G, WLAN 5.1G, WLAN 5.8G, WLAN Display. Bluetooth Version: Bluetooth v5.1",
            "Fingerprint (under display, optical), accelerometer, gyro, proximity, compass",
        ],
        v1Price: 199,
        catagories: "mobile",
        id: '6545456FGHFDGHFG54RY5456TYTFHYT',
        rating: 3.2,
        numOfReviews: 12,
    },
    {
        title: "realme 7 Pro 8GB/128GB",
        img: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/r/e/realme-7-pro-4.jpg",
        img2: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/r/e/realme-7-pro-6.jpg",
        img3: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/r/e/realme-7-pro-5.jpg",
        img4: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/r/e/realme-7-pro.jpg",
        img5: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/r/e/realme-7-pro-3.jpg",
        brand: "realme",
        variant: [
            "128GB",
        ],
        featuresTitle: [
            "OS",
            "CPU",
            "CPU Cores",
            "GPU",
            "RAM",
            "ROM",
            "Rear Camera",
            "Front Camera",
            "Screen",
            "Display Panel",
            "Resolution",
            "Battery",
            "Connectivity",
            "",
            "Sensors",
        ],

        featuresValue: [
            "ColorOS 7.2 (Based on Android 10)",
            "MediaTek Helio P95",
            "Octa-core",
            "IMG 9XM-HP8 970MHz",
            "8GB",
            "128 GB",
            "48MP+8MP+2MP+2MP",
            "16MP+2MP",
            "6.43 inches",
            "Super AMOLED",
            "2400*1080 (Refresh Rate: up to 60Hz)",
            " Non-removable Li-Po 4015 mAh battery (Fast Charge: VOOC 4.0)",
            "WLAN 2.4G, WLAN 5.1G, WLAN 5.8G, WLAN Display. Bluetooth Version: Bluetooth v5.1",
            "Fingerprint (under display, optical), accelerometer, gyro, proximity, compass",
        ],
        v1Price: 219,
        id: '689779789987879987FGHGBNFGHFGH',
        catagories: "mobile",
    },
    {
        title: "realme 7i 8GB/128GB",
        img: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/r/e/realme-7i-2.jpg",
        img2: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/r/e/realme-7i-3.jpg",
        img3: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/r/e/realme-7i.jpg",
        img4: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/r/e/realme-7i-4.jpg",
        img5: "",
        brand: "realme",
        variant: [
            "128GB",
        ],
        featuresTitle: [
            "OS",
            "CPU",
            "CPU Cores",
            "GPU",
            "RAM",
            "ROM",
            "Rear Camera",
            "Front Camera",
            "Screen",
            "Display Panel",
            "Resolution",
            "Battery",
            "Connectivity",
            "",
            "Sensors",
        ],

        featuresValue: [
            "ColorOS 7.2 (Based on Android 10)",
            "MediaTek Helio P95",
            "Octa-core",
            "IMG 9XM-HP8 970MHz",
            "8GB",
            "128 GB",
            "48MP+8MP+2MP+2MP",
            "16MP+2MP",
            "6.43 inches",
            "Super AMOLED",
            "2400*1080 (Refresh Rate: up to 60Hz)",
            " Non-removable Li-Po 4015 mAh battery (Fast Charge: VOOC 4.0)",
            "WLAN 2.4G, WLAN 5.1G, WLAN 5.8G, WLAN Display. Bluetooth Version: Bluetooth v5.1",
            "Fingerprint (under display, optical), accelerometer, gyro, proximity, compass",
        ],
        v1Price: 159,
        id: 'IUYOOIJUHHJJH0677676',
        catagories: "mobile",
        rating: 3.2,
        numOfReviews: 12,
    },
    {
        title: "realme C11 2GB/32GB",
        img: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/r/e/realme-c11.jpg",
        img2: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/r/e/realme-c11-7.jpg",
        img3: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/r/e/realme-c11-3.jpg",
        img4: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/r/e/realme-c11-4.jpg",
        img5: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/r/e/realme-c11-5.jpg",
        brand: "realme",
        variant: [
            "32GB",
        ],
        featuresTitle: [
            "OS",
            "CPU",
            "CPU Cores",
            "GPU",
            "RAM",
            "ROM",
            "Rear Camera",
            "Front Camera",
            "Screen",
            "Display Panel",
            "Resolution",
            "Battery",
            "Connectivity",
            "",
            "Sensors",
        ],

        featuresValue: [
            "ColorOS 7.2 (Based on Android 10)",
            "MediaTek Helio P95",
            "Octa-core",
            "IMG 9XM-HP8 970MHz",
            "8GB",
            "128 GB",
            "48MP+8MP+2MP+2MP",
            "16MP+2MP",
            "6.43 inches",
            "Super AMOLED",
            "2400*1080 (Refresh Rate: up to 60Hz)",
            " Non-removable Li-Po 4015 mAh battery (Fast Charge: VOOC 4.0)",
            "WLAN 2.4G, WLAN 5.1G, WLAN 5.8G, WLAN Display. Bluetooth Version: Bluetooth v5.1",
            "Fingerprint (under display, optical), accelerometer, gyro, proximity, compass",
        ],
        v1Price: 129,
        id: 'TE45TDFG456TYFDT56654665665',
        catagories: "mobile",
        rating: 3.2,
        numOfReviews: 12,
    },
    {
        title: "realme 6 8GB/128GB",
        img: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/r/e/realme-6.jpg",
        img2: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/r/e/realme-6-2.jpg",
        img3: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/r/e/realme-6-5.jpg",
        img4: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/a4a71470c99ce7a4925275fbc94e38e5/r/e/realme-6-4_1_1.jpg",
        img5: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/a4a71470c99ce7a4925275fbc94e38e5/r/e/realme-6-3_1_1.jpg",
        brand: "realme",
        variant: [
            "128GB",
        ],
        featuresTitle: [
            "OS",
            "CPU",
            "CPU Cores",
            "GPU",
            "RAM",
            "ROM",
            "Rear Camera",
            "Front Camera",
            "Screen",
            "Display Panel",
            "Resolution",
            "Battery",
            "Connectivity",
            "",
            "Sensors",
        ],

        featuresValue: [
            "ColorOS 7.2 (Based on Android 10)",
            "MediaTek Helio P95",
            "Octa-core",
            "IMG 9XM-HP8 970MHz",
            "8GB",
            "128 GB",
            "48MP+8MP+2MP+2MP",
            "16MP+2MP",
            "6.43 inches",
            "Super AMOLED",
            "2400*1080 (Refresh Rate: up to 60Hz)",
            " Non-removable Li-Po 4015 mAh battery (Fast Charge: VOOC 4.0)",
            "WLAN 2.4G, WLAN 5.1G, WLAN 5.8G, WLAN Display. Bluetooth Version: Bluetooth v5.1",
            "Fingerprint (under display, optical), accelerometer, gyro, proximity, compass",
        ],
        v1Price: 209,
        id: '432324WERRFDDF34DSFF453RFFDF',
        catagories: "mobile",
        rating: 3.2,
        numOfReviews: 12,
    },
    {
        title: "Huawei nova 5T 8GB/128GB",
        img: "https://consumer-img.huawei.com/content/dam/huawei-cbg-site/common/mkt/pdp/phones/nova-5t/img/huawei-nova-5T.jpg",
        img2: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/h/u/huawei-nova-5t-8gb-128gb-crush-blue.jpg",
        img3: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/h/u/huawei-nova-5t-8gb-128gb-crush-blue-1.jpg",
        img4: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/h/u/huawei-nova-5t-8gb-128gb-crush-blue-2.jpg",
        img5: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/h/u/huawei-nova-5t-8gb-128gb-crush-blue-3.jpg",
        brand: "Huawei",
        variant: [
            "128GB",
        ],
        featuresTitle: [
            "OS",
            "CPU",
            "CPU Cores",
            "GPU",
            "RAM",
            "ROM",
            "Rear Camera",
            "Front Camera",
            "Screen",
            "Display Panel",
            "Resolution",
            "Battery",
            "Connectivity",
            "",
            "Sensors",
        ],

        featuresValue: [
            "ColorOS 7.2 (Based on Android 10)",
            "MediaTek Helio P95",
            "Octa-core",
            "IMG 9XM-HP8 970MHz",
            "8GB",
            "128 GB",
            "48MP+8MP+2MP+2MP",
            "16MP+2MP",
            "6.43 inches",
            "Super AMOLED",
            "2400*1080 (Refresh Rate: up to 60Hz)",
            " Non-removable Li-Po 4015 mAh battery (Fast Charge: VOOC 4.0)",
            "WLAN 2.4G, WLAN 5.1G, WLAN 5.8G, WLAN Display. Bluetooth Version: Bluetooth v5.1",
            "Fingerprint (under display, optical), accelerometer, gyro, proximity, compass",
        ],
        v1Price: 259,
        id: 'ET456546565665DRFAS55W',
        catagories: "mobile",
        rating: 3.2,
        numOfReviews: 12,
    },
    {
        title: "Huawei P40 Pro 5G 8GB/256GB",
        img: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/h/u/huawei-p40-pro-blue-4.jpg",
        img2: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/h/u/huawei-p40-pro-blue-3.jpg",
        img3: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/h/u/huawei-p40-pro-blue-2.jpg",
        img4: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/h/u/huawei-p40-pro-blue.jpg",
        img5: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/h/u/huawei-p40-pro-silver.jpg",
        brand: "Huawei",
        variant: [
            "256GB",
        ],
        featuresTitle: [
            "OS",
            "CPU",
            "CPU Cores",
            "GPU",
            "RAM",
            "ROM",
            "Rear Camera",
            "Front Camera",
            "Screen",
            "Display Panel",
            "Resolution",
            "Battery",
            "Connectivity",
            "",
            "Sensors",
        ],

        featuresValue: [
            "ColorOS 7.2 (Based on Android 10)",
            "MediaTek Helio P95",
            "Octa-core",
            "IMG 9XM-HP8 970MHz",
            "8GB",
            "128 GB",
            "48MP+8MP+2MP+2MP",
            "16MP+2MP",
            "6.43 inches",
            "Super AMOLED",
            "2400*1080 (Refresh Rate: up to 60Hz)",
            " Non-removable Li-Po 4015 mAh battery (Fast Charge: VOOC 4.0)",
            "WLAN 2.4G, WLAN 5.1G, WLAN 5.8G, WLAN Display. Bluetooth Version: Bluetooth v5.1",
            "Fingerprint (under display, optical), accelerometer, gyro, proximity, compass",
        ],
        v1Price: 999,
        id: 'ERTERTY4576RE544665656665546',
        catagories: "mobile",
        rating: 2.3,
        numOfReviews: 12,
    },
    {
        title: "Apple iPhone 12 128GB",
        img: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/a/p/apple-iphone-12--10_1.jpg",
        img2: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/a/p/apple-iphone-12--13_1.jpg",
        img3: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/a/p/apple-iphone-12--9_1.jpg",
        img4: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/a/p/apple-iphone-12--4_1.jpg",
        img5: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/a/p/apple-iphone-12_1.jpg",
        brand: "Apple",
        variant: [
            "128GB",
        ],
        featuresTitle: [
            "OS",
            "CPU",
            "CPU Cores",
            "GPU",
            "RAM",
            "ROM",
            "Rear Camera",
            "Front Camera",
            "Screen",
            "Display Panel",
            "Resolution",
            "Battery",
            "Connectivity",
            "",
            "Sensors",
        ],

        featuresValue: [
            "IOS",
            "Apple A14",
            "Octa-core",
            "IMG 9XM-HP8 970MHz",
            "4GB",
            "128 GB",
            "48MP+8MP+2MP+2MP",
            "16MP+2MP",
            "6.43 inches",
            "Super AMOLED",
            "2400*1080 (Refresh Rate: up to 60Hz)",
            " Non-removable Li-Po 4015 mAh battery (Fast Charge: VOOC 4.0)",
            "WLAN 2.4G, WLAN 5.1G, WLAN 5.8G, WLAN Display. Bluetooth Version: Bluetooth v5.1",
            "Fingerprint (under display, optical), accelerometer, gyro, proximity, compass",
        ],
        v1Price: 799,
        id: 'SDRFER435645DRFGERT45656',
        catagories: "mobile",
    },
    {
        title: "Apple iPhone 11 Pro 256GB",
        img: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/i/p/iphone11-pro-space-grey-256.jpg",
        img2: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/i/p/iphone11-pro-space-grey-256-1.jpg",
        img3: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/i/p/iphone11-pro-gold-256.jpg",
        img4: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/i/p/iphone11-pro-midnight-green-256.jpg",
        img5: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/i/p/iphone11-pro-silver-256.jpg",
        brand: "Apple",
        variant: [
            "256GB",
        ],
        featuresTitle: [
            "OS",
            "CPU",
            "CPU Cores",
            "GPU",
            "RAM",
            "ROM",
            "Rear Camera",
            "Front Camera",
            "Screen",
            "Display Panel",
            "Resolution",
            "Battery",
            "Connectivity",
            "",
            "Sensors",
        ],

        featuresValue: [
            "ColorOS 7.2 (Based on Android 10)",
            "MediaTek Helio P95",
            "Octa-core",
            "IMG 9XM-HP8 970MHz",
            "8GB",
            "128 GB",
            "48MP+8MP+2MP+2MP",
            "16MP+2MP",
            "6.43 inches",
            "Super AMOLED",
            "2400*1080 (Refresh Rate: up to 60Hz)",
            " Non-removable Li-Po 4015 mAh battery (Fast Charge: VOOC 4.0)",
            "WLAN 2.4G, WLAN 5.1G, WLAN 5.8G, WLAN Display. Bluetooth Version: Bluetooth v5.1",
            "Fingerprint (under display, optical), accelerometer, gyro, proximity, compass",
        ],
        v1Price: 1199,
        id: 'FHBGHD4WER5345SDFFG',
        catagories: "mobile",
    },
    {
        title: "Apple iPhone X 256GB",
        img: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/a/p/apple-iphone-x-silvevr_1.jpg",
        img2: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/a/p/apple-iphone-x-grey_1.jpg",
        img3: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/i/-/i-phone-x-camera.jpg",
        img4: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/i/-/i-phone-x-front-back.jpg",
        img5: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/i/-/i-phone-x-front-panel.jpg",
        brand: "Apple",
        variant: [
            "256GB",
        ],
        featuresTitle: [
            "OS",
            "CPU",
            "CPU Cores",
            "GPU",
            "RAM",
            "ROM",
            "Rear Camera",
            "Front Camera",
            "Screen",
            "Display Panel",
            "Resolution",
            "Battery",
            "Connectivity",
            "",
            "Sensors",
        ],

        featuresValue: [
            "ColorOS 7.2 (Based on Android 10)",
            "MediaTek Helio P95",
            "Octa-core",
            "IMG 9XM-HP8 970MHz",
            "8GB",
            "128 GB",
            "48MP+8MP+2MP+2MP",
            "16MP+2MP",
            "6.43 inches",
            "Super AMOLED",
            "2400*1080 (Refresh Rate: up to 60Hz)",
            " Non-removable Li-Po 4015 mAh battery (Fast Charge: VOOC 4.0)",
            "WLAN 2.4G, WLAN 5.1G, WLAN 5.8G, WLAN Display. Bluetooth Version: Bluetooth v5.1",
            "Fingerprint (under display, optical), accelerometer, gyro, proximity, compass",
        ],
        v1Price: 999,
        id: 'DFRGDFTGHASYURTYT3D5456SW',
        catagories: "mobile",
    },
    {
        title: "Apple iPhone 12 Pro 128GB",
        img: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/a/p/apple-iphone-pro--13.jpg",
        img2: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/a/p/apple-iphone-pro--3.jpg",
        img3: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/a/p/apple-iphone-pro.jpg",
        img4: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/a/p/apple-iphone-pro--5.jpg",
        img5: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/a/p/apple-iphone-pro--9.jpg",
        brand: "Apple",
        variant: [
            "128GB",
        ],
        featuresTitle: [
            "OS",
            "CPU",
            "CPU Cores",
            "GPU",
            "RAM",
            "ROM",
            "Rear Camera",
            "Front Camera",
            "Screen",
            "Display Panel",
            "Resolution",
            "Battery",
            "Connectivity",
            "",
            "Sensors",
        ],

        featuresValue: [
            "ColorOS 7.2 (Based on Android 10)",
            "MediaTek Helio P95",
            "Octa-core",
            "IMG 9XM-HP8 970MHz",
            "8GB",
            "128 GB",
            "48MP+8MP+2MP+2MP",
            "16MP+2MP",
            "6.43 inches",
            "Super AMOLED",
            "2400*1080 (Refresh Rate: up to 60Hz)",
            " Non-removable Li-Po 4015 mAh battery (Fast Charge: VOOC 4.0)",
            "WLAN 2.4G, WLAN 5.1G, WLAN 5.8G, WLAN Display. Bluetooth Version: Bluetooth v5.1",
            "Fingerprint (under display, optical), accelerometer, gyro, proximity, compass",
        ],
        v1Price: 899,
        id: 'WERXDFFG34EERFVED4R3543554354',
        catagories: "mobile",
    },
    {
        title: "Redmi Note 9 Pro 6GB/128GB",
        img: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/r/e/redmi-note-9-pro-2_1.jpg",
        img2: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/r/e/redmi-note-9-pro-4_1.jpg",
        img3: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/r/e/redmi-note-9-pro-5_1.jpg",
        img4: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/r/e/redmi-note-9-pro-6_1_1.jpg",
        img5: "https://b2b-pickaboocdn.s3-ap-southeast-1.amazonaws.com/media/catalog/product/cache/c9c3ae6e3f78df4924e8b3b9bf50d8e7/r/e/redmi-note-9-pro-7_1.jpg",
        brand: "Redmi",
        variant: [
            "128GB",
        ],
        featuresTitle: [
            "OS",
            "CPU",
            "CPU Cores",
            "GPU",
            "RAM",
            "ROM",
            "Rear Camera",
            "Front Camera",
            "Screen",
            "Display Panel",
            "Resolution",
            "Battery",
            "Connectivity",
            "",
            "Sensors",
        ],

        featuresValue: [
            "ColorOS 7.2 (Based on Android 10)",
            "MediaTek Helio P95",
            "Octa-core",
            "IMG 9XM-HP8 970MHz",
            "8GB",
            "128 GB",
            "48MP+8MP+2MP+2MP",
            "16MP+2MP",
            "6.43 inches",
            "Super AMOLED",
            "2400*1080 (Refresh Rate: up to 60Hz)",
            " Non-removable Li-Po 4015 mAh battery (Fast Charge: VOOC 4.0)",
            "WLAN 2.4G, WLAN 5.1G, WLAN 5.8G, WLAN Display. Bluetooth Version: Bluetooth v5.1",
            "Fingerprint (under display, optical), accelerometer, gyro, proximity, compass",
        ],
        v1Price: 229,
        id: 'QARTATRRRDRFAS56543DSW',
        catagories: "mobile",
    },
]


// {
//     title: "",
//     img: "",
//     img2: "",
//     img3: "",
//     img4: "",
//     img5: "",
//     brand: "",
//     variant: [
//         "",
//     ],
//     featuresTitle: [
//         "",
//     ],
//     featuresValue: [
//         "",
//     ],
//     about: [
//         "",
//     ],
//     v1Price: ,
//     catagories: "",
//     id: '',
// },


export default mobile;